name: rf_majid
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  bottom_sheet: ^3.1.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  custom_check_box: ^0.0.4
  dropdown_button2: ^1.9.2
  empty_widget: ^0.0.5
  fancy_bottom_navigation: ^0.3.3
  firebase_auth: ^4.2.0
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.10
  firestore_cache: ^2.3.0
  flutter:
    sdk: flutter
  flutter_beautiful_popup: ^1.7.0
  flutter_counter_pack: ^0.0.1
  flutter_custom_dialog: ^1.3.0
  flutter_datetime_picker: ^1.5.1
  flutter_filter_dialog: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: ^3.0.2
  flutter_secure_storage: ^7.0.1
  get: 4.6.5
  getwidget: ^3.0.1
  google_sign_in: ^5.4.2
  iconify_flutter: ^0.0.5
  iconsax: ^0.0.8
  image_picker: ^0.8.6+1
  intl: ^0.17.0
  material_dialogs: ^1.1.4
  panara_dialogs: ^0.1.4
  permission_handler: ^10.2.0
  quickalert: ^1.0.1
  rflutter_alert: ^2.0.4
  standard_dialogs: ^2.0.0
  stylish_dialog: ^1.0.1
  flutter_svg:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/gambar/logo_2.png
    - assets/gambar/logo_1.png
    - assets/gambar/Screenshot_4.png
    - assets/gambar/Screenshot_3.png
    - assets/gambar/Screenshot_2.png
    - assets/gambar/Screenshot_1.png
    - assets/gambar/minuman.png
    - assets/gambar/gambar1.png
    - assets/gambar/gambar2.jpg
    - assets/gambar/gambar3.jpg
    - assets/gambar/profile.png
    - assets/gambar/8401.jpg
    - assets/splash.png
    - assets/splash_2.png
    - assets/on_boarding/
  uses-material-design: true
  fonts:
    - family: Sofia Sans Condensed
      fonts:
        - asset: assets/fonts/SofiaSansSemiCondensed-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/SofiaSansSemiCondensed-VariableFont_wght.ttf
          weight: 700
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Light.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
