// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfyzUdD0J609VXqwT3azxQCU50sTsnk9c',
    appId: '1:841866151526:web:7b75ebabdaf8380b0e8fa7',
    messagingSenderId: '841866151526',
    projectId: 'majidin-27602',
    authDomain: 'majidin-27602.firebaseapp.com',
    storageBucket: 'majidin-27602.appspot.com',
    measurementId: 'G-D74DW0CS1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNofrmyvnVBSf49aNFKeQOJu_RFUdUXtY',
    appId: '1:841866151526:android:7c856eb49a489d2e0e8fa7',
    messagingSenderId: '841866151526',
    projectId: 'majidin-27602',
    storageBucket: 'majidin-27602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS5DTCu1PmIBScS8uMgYgKJaYX4sWTNNE',
    appId: '1:841866151526:ios:d0dc7cb8cfbb48fd0e8fa7',
    messagingSenderId: '841866151526',
    projectId: 'majidin-27602',
    storageBucket: 'majidin-27602.appspot.com',
    iosClientId: '841866151526-m21dduqganha4pvk56sv55of6g7jpbt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rfMajid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS5DTCu1PmIBScS8uMgYgKJaYX4sWTNNE',
    appId: '1:841866151526:ios:d0dc7cb8cfbb48fd0e8fa7',
    messagingSenderId: '841866151526',
    projectId: 'majidin-27602',
    storageBucket: 'majidin-27602.appspot.com',
    iosClientId: '841866151526-m21dduqganha4pvk56sv55of6g7jpbt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rfMajid',
  );
}
